services:
    content_scheduler.publishing.scheduler:
        class: SymfonyContrib\Bundle\ContentSchedulerBundle\ScheduledPublishing\PublishingScheduler
        arguments:
            - "@doctrine.orm.entity_manager"

    content_scheduler.doctrine.event_subscriber:
        class: SymfonyContrib\Bundle\ContentSchedulerBundle\Doctrine\EventSubscriber
        tags:
            - name: doctrine.event_subscriber

    content_scheduler.form.type.publishing:
        class: SymfonyContrib\Bundle\ContentSchedulerBundle\Form\Type\ScheduledPublishingType
        arguments:
            - "@content_scheduler.publishing.scheduler"
        tags:
            - name: form.type
